environment: stg
replicaCount: 2
profile: sandbox-k8
maxUnavailable: 0
jmxPort: 1099
memoryRequest: 1024Mi
memoryLimit: 2048Mi
cpuRequest: 1000m
cpuLimit: 2000m
imagePullPolicy: Always
newRelicLicense: ba763ed24ac1c845380ee5faecf0e29b5801f7f4