---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rcbse-{{ .Values.environment }}-legacy
  namespace: bsre
  labels:
    app.kubernetes.io/name: bsre-legacy-api-{{ .Values.environment }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: bsre-legacy-api-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bsre-legacy-api-{{ .Values.environment }}
      annotations:
        checksum/config: {{ randAlphaNum 32 | quote }}
    spec:
      containers:
      - name: webapp
        image: "gcr.io/redeo-all/realestate-bsre-legacy:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        resources:
          limits:
            memory: "{{ .Values.memoryLimit }}"
            cpu: "{{ .Values.cpuLimit }}"
          requests:
            memory: "{{ .Values.memoryRequest }}"
            cpu: "{{ .Values.cpuRequest }}"
        livenessProbe:
          httpGet:
            path: /manage/health
            port: http-alt
          initialDelaySeconds: 100
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /manage/health
            port: http-alt
          initialDelaySeconds: 100
          periodSeconds: 15
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
          name: http-alt
        - containerPort: 1099
          name: jmx
        - containerPort: 10051
          name: zabbix-active
        envFrom:
        - configMapRef:
            name: bsre-legacy-{{ .Values.environment }}-{{ .Values.image.tag | lower }}
        env:
        - name: JMX_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: JMX_PORT
          value: "1099"
      - name: zabbix-agent
        image: "gcr.io/redeo-all/docker-zabbix-agent:1.0.7"
        lifecycle:
          postStart:
            exec:
              command: 
              - "/etc/zabbix/zabbix_api.sh"
              - "createOrUpdate"
          preStop:
            exec:
              command:
              - "/etc/zabbix/zabbix_api.sh"
              - "disable"
        ports:
        - containerPort: 10050
          name: zabbix-pasive
        envFrom:
        - configMapRef:
            name: bsre-legacy-{{ .Values.environment }}-{{ .Values.image.tag | lower }}